### ISSUE TITLE
local folder 7za.exe not detected

### ISSUE THREAD

**Issue by Luckz** [XhmikosR/slim-nvidia-drivers#2]
This doesn't actually seem to work with 7za.exe (32 or 64bit) _in the same folder as the bat file_.
As a workaround, I added the following line: `set "SEVENZIP=%~dp0\7za.exe"` (for example at line 223)
Without the dp0 it can only extract, but then not create the zip, due to not going back to the .bat file's folder after leaving it.

**Comment by XhmikosR** [comment]
You can submit a proper PR which doesn't break anything and I can review, otherwise I have no time to look into this.

**Comment by Luckz** [comment]
I figured, and that was my initial idea.
My bat-fu is not strong enough to get through `for %%G in (7za.exe) do (set "SEVENZIP_PATH=%%~$PATH:G")`.

**Comment by XhmikosR** [comment]
Should be fixed by https://github.com/XhmikosR/slim-nvidia-drivers/commit/3bb104905799915f9995e85182b2ddcb7c45c2a7
